# [START app_yaml]
service: ginquest-backend
env: flex
runtime: nodejs

endpoints_api_service:
  name: ginquest-backend-dot-ginquest-app.appspot.com
  rollout_strategy: managed

beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: ginquest-app:us-central1:ginquest
