swagger: "2.0"
info:
  description: "A simple Google Cloud Endpoints API example."
  title: "Endpoints Example"
  version: "1.0.0"
host: "ginquest-backend-dot-ginquest-app.appspot.com"
consumes:
  - "application/json"
produces:
  - "application/json"
schemes:
  - "https"
paths:
  "/hello":
    get:
      description: "Returns the requests' authentication information."
      operationId: "hello"
      produces:
        - "application/json"
      responses:
        200:
          description: "Authenication info."
  "/":
    get:
      description: "Returns the requests' authentication information."
      operationId: "hello world"
      produces:
        - "application/json"
      responses:
        200:
          description: "Authenication info."
  "/quiz":
    get:
      description: "Returns the requests' authentication information."
      operationId: "quiz"
      produces:
        - "application/json"
      responses:
        200:
          description: "Authenication info."
